name: Super-Linter and Docker Build, Push

on: push

jobs:
  super-lint:
    name: List code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Qemu
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to hub.docker.com
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
         push: true
         tags: legendmt25/kiii-jenkins:latest